export const QUERY_KEYS = {
  GET_EMPLOYEES: 'get-employees',
  GET_ROLES: 'get-roles',
  GET_MENUS: 'get-menus',
  GET_ROLES_PERMISSIONS: 'get-roles-permissions',
  GET_ROLES_PERMISSIONS_V2: 'get-roles-permissions-v2',
  GET_TEAMS: 'get-teams',
  GET_ALL_TIMEKEEPING: 'get-all-timekeeping',
  GET_ALL_REQUESTS: 'get-all-requests',
  GET_PROFILE: 'get-profile',
  GET_ATTENDANCE_DETAIL: 'get-attendance-detail',
  GET_ATTENDANCE_REQUEST_BY_ATTENDANCE_ID: 'get-attendance-request-by-attendance-id',
  GET_TIMEKEEPING_STATISTICS: 'get-timekeeping-statistics',
  GET_ALL_DEPARTMENT: 'get-all-department',
  EXPORT_EXCEL_TIMEKEEPING: 'export-excel-timekeeping',
  GET_ORGANIZATION_CHART: 'get-organization-chart',
  GET_PENDING_APPOVALS: 'get-pending-approvals',
  GET_APPROVED_REQUESTS: 'get-approved-requests',
  GET_PENDING_REQUESTS_BY_USER: 'get-pending-requests-by-user',
  GET_REQUEST_EMPLOYEE_BY_ID: 'get-request-employee-by-id',
  GET_APPROVED_REQUESTS_EMPLOYEE: 'get-approved-requests-employee',
  GET_REQUEST_REFERENCES_BY_USER: 'get-request-references-by-user',
  GET_UNSEEN_COUNT_REQ_REF: 'get-unseen-count-req-ref',
  GET_COUNT_PENDING_REQUEST_EMPLOYEE: 'get-count-pending-request-employee',
  GET_COUNT_PENDING_APPROVE_REQUEST: 'get-count-pending-approve-request',
  GET_EMPLOYEES_SCHEDULE: 'get-employee-schedule',
  EXPORT_EXCEL_WORK_SCHEDULE: 'get-excel-work-schedule',
};
